//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace  WxPay2017.API.DAL.EmpModels
{
     using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Message.Message")]
    public partial class Message
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message()
        {
            MessageRecords = new HashSet<MessageRecord>();
            CreateDate = DateTime.Now;
          
        }

        public int Id { get; set; }

        public int MessageTypeId { get; set; }

        public DateTime CreateDate { get; set; }

       
        public DateTime? EndDate { get; set; }
        
        public int MessageSourceTypeId { get; set; }

        [Required]
        [StringLength(128)]
        public string SrcId { get; set; }

        [Required]
        [StringLength(200)]
        public string Subject { get; set; }

        public string Body { get; set; }

        [StringLength(1024)]
        public string Url { get; set; }

        public DateTime ActiveDate { get; set; }

        public bool IsDeleted { get; set; }

        public DateTime NotActiveDate { get; set; }
        public int? AlertLevelId { get; set; }
      
       public virtual Dictionary MessageType { get; set; }
        
        public virtual Dictionary MessageSourceType { get; set; }
           [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Display(Name = "消息发送详单")]
        public virtual ICollection<MessageRecord> MessageRecords { get; set; }
    }
}

    