//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace  WxPay2017.API.DAL.EmpModels
{
     using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Meter.MeterStatus")]
    public partial class MeterStatus
    {
        public MeterStatus()
        {
           
        }
        [Key]
        public int Id { get; set; }

        public int MeterId { get; set; }

        public int MeterMessageTypeId { get; set; }

        public bool Enabled { get; set; }

        public decimal Value { get; set; }
        [StringLength(400)]
        public string Description { get; set; }
        public DateTime UpdateTime { get; set; }

        public bool? IsFluctuationData { get; set; }

        public int? MonitoringConfigId { get; set; }

        public virtual Dictionary MeterMessageType { get; set; }

        public virtual Meter Meter { get; set; }

       // public virtual MonitoringConfig MonitoringConfig { get; set; }
    }
}

