//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace  WxPay2017.API.DAL.EmpModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Foundation.MonitoringConfig")]
    public partial class MonitoringConfig
    {
        public MonitoringConfig()
        {
           // MeterStatuses = new HashSet<MeterStatus>();
            //ConfigDetails = new HashSet<ConfigDetail>();
            ConfigDetailTemplates = new HashSet<ConfigDetail>();
            ConfigDetailHolidayTimeControlTemplates = new HashSet<ConfigDetail>();
            ConfigDetailPeacetimeTimeControlTemplates = new HashSet<ConfigDetail>();
          
            ConfigDetailVacationTimeControlTemplates = new HashSet<ConfigDetail>();
            
            ConfigDetailWeekEndTimeControlTemplates = new HashSet<ConfigDetail>();
        }

        public int Id { get; set; }

        [StringLength(100)]
        public string Name { get; set; }

        [StringLength(400)]
        public string Description { get; set; }

        public int TargetTypeId { get; set; }

        public int TargetId { get; set; }

        public int? EnergyCategoryId { get; set; }

        public int ConfigTypeId { get; set; }

        public int? WayId { get; set; }

        public decimal? UnitValue { get; set; }

        public decimal? LowerLimit { get; set; }

        public decimal? UpperLimit { get; set; }

        public decimal? Value { get; set; }

        public DateTime? ValidStartTime { get; set; }

        public DateTime? ValidEndTime { get; set; }

        public int? Priority { get; set; }

        public bool Enabled { get; set; }

        public DateTime StartTime { get; set; }

        public DateTime EndTime { get; set; }

        [StringLength(128)]
        public string RegeneratorId { get; set; }

        [StringLength(256)]
        public string RegeneratorName { get; set; }

        public DateTime? UpdatingTime { get; set; }

        public int? ParameterId { get; set; }

        public DateTime? CycleTime { get; set; }

        public int? CycleTypeId { get; set; }

        public int? AlarmLevelId { get; set; }
        public int? ValidTypeId { get; set; }
        public int? TemplateId { get; set; }
        public DateTime? OverTimeDate { get; set; }
        public bool? IsvalidNextCycle { get; set; }

        [Display(Name = "告警检测周期类型")]
        public virtual Dictionary ValidType { get; set; }
       [Display(Name = "能耗类型")]
        public virtual Dictionary EnergyCategory { get; set; }
       [Display(Name = "配置类型")]
       public virtual Dictionary TargetType { get; set; }
        [Display(Name = "循环分类")]
        public virtual Dictionary CycleType { get; set; }
       [Display(Name = "告警等级")]
        public virtual Dictionary AlarmLevel { get; set; }
        [Display(Name = "设置分类")]
       public virtual Dictionary Way { get; set; }
       [Display(Name = "修改者")]
        public virtual User Regenerator { get; set; }
        public virtual Dictionary ConfigType { get; set; }
        public virtual Parameter Parameter { get; set; }
        //public virtual ICollection<MeterStatus> MeterStatuses { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SceneModeConfig> SceneModeConfigs { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigCycleSetting> ConfigCycleSettings { get; set; }

        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<ConfigDetail> ConfigDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigDetail> ConfigDetailTemplates { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigDetail> ConfigDetailHolidayTimeControlTemplates { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigDetail> ConfigDetailPeacetimeTimeControlTemplates { get; set; }

       

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigDetail> ConfigDetailVacationTimeControlTemplates { get; set; }

        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigDetail> ConfigDetailWeekEndTimeControlTemplates { get; set; }


    }
}
