//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace  WxPay2017.API.DAL.EmpModels
{
     using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Message.Subscribe")]
    public partial class Subscribe
    {
        public Subscribe()
        {
        }
        public int Id { get; set; }

        public int TypeId { get; set; }

        [StringLength(100)]
        public string Name { get; set; }

        [StringLength(400)]
        public string Description { get; set; }

        public int TargetTypeId { get; set; }

        [Required]
        [StringLength(128)]
        public string TargetId { get; set; }

        public bool Enabled { get; set; }

        public int MessageTypeId { get; set; }
        public int ReceivingModelId { get; set; }
        public virtual Dictionary ReceivingModel { get; set; }
        public virtual Dictionary Type { get; set; }
        public virtual Dictionary TargetType { get; set; }
        public virtual Dictionary MessageType { get; set; }
    }
}
